repos:
################################################################################
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=10000']
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
################################################################################
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -   id: black-jupyter
        args: ['--line-length', '79']
        language_version: python3
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ['--profile', 'black',
               '--line-length', '79']
-   repo: https://github.com/numpy/numpydoc
    rev: v1.7.0
    hooks:
    -   id: numpydoc-validation
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: ['--ignore=E741', '--ignore=E731', '--fix']
################################################################################
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
    -   id: actionlint
################################################################################
-   repo: https://github.com/crate-ci/typos
    rev: v1.21.0
    hooks:
    -   id: typos
        args: ["--force-exclude"]
################################################################################
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
    -   id: commitizen
################################################################################
